
// CART
export const INIT_CART = 'INIT_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';

// SEARCH
export const INIT_SEARCH_BAR = 'INITSEARCH_BAR'


// PRODUCTS
export const UPDATE_SINGLE_PRODUCT_PAGINATION = 'UPDATE_SINGLE_PRODUCT_PAGINATION';
export const STORE_PRODUCTS = 'STORE_PRODUCTS';


// USER 
export const STORE_LOGGEDIN_USER = 'STORE_LOGGEDIN_USER';
export const UPDATE_USER_CART = 'UPDATE_USER_CART';
export const UPDATE_USER_CART_FAIL = 'UPDATE_USER_CART_FAIL';
export const ADD_ITEM_TO_USER_CART = 'ADD_ITEM_TO_USER_CART';
export const REMOVE_ITEM_FROM_USER_CART = 'REMOVE_ITEM_FROM_USER_CART';



// MOBILE MENU
export const INIT_MOBILE_MENU = 'INIT_MOBILE_MENU'