
// CART
export const INIT_CART = 'INIT_CART';
export const ADD_TO_CART = 'ADD_TO_CART';


// PRODUCTS
export const UPDATE_SINGLE_PRODUCT_PAGINATION = 'UPDATE_SINGLE_PRODUCT_PAGINATION';
export const STORE_PRODUCTS = 'STORE_PRODUCTS';